version: '2'
services:

  web:
    container_name: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-production
    ports:
     - "8443:8443"
    #-"443:443"
    volumes:
     - ./www:/var/www/html